### ISSUE TITLE
JITStreamer-2.0 / Linux + iPad / WiFi OK, Hotspot OK, Cellular Error - tun0 never created.

### ISSUE THREAD

**Issue by jorycz** [stossy11/JITStreamer-2.0#15]
I just setup CT (Debian 12) on Proxmox version 8 with Device Passthrough (iPad) for pairing and installed Wireguard VPN which is very easy to setup on CT (server) and on iPad (client).
iPad Pro is M2 model with version 18.0.1 and iPhone is 15 Pro with also 18.0.1.
**I have SIM card in my iPad.**

When I start JITStreamer on CT and iPad is on local WiFi without Wireguard, it works as expected. tun0 is created (in CT), tunnel established, JIT Enabled.

When I start JITStreamer on CT when Wireguard is already connected, iPad using own cellular and I choose Enable JIT from Shortcut, tap0 device should be created (tunnel) but it is not, and this message (which is kind of expected) follows:

```
INFO:     127.0.0.1:33422 - "GET /start-tunnel?ip=10.0.100.2&udid=00008112-000AXXXXXXXXXXXX&connection_type=usbmux-tcp HTTP/1.1" 501 Not Implemented                   
INFO:     127.0.0.1:33438 - "GET / HTTP/1.1" 200 OK                                                                                                                    
WARNING:root:No devices returned from get_tunneld_devices().                                                                                                           
INFO:werkzeug:10.0.100.2 - - [15/Oct/2024 00:17:01] "GET /00008112-000AXXXXXXXXXXXX/ HTTP/1.1" 404 -
```

But 3rd scenario is interesting.

When I start JITStreamer on CT when Wireguard is already connected, but iPad is connected to internet **using iPhone hotspot** - **tun0 is created, tunnel established and JIT Enabled**.
It **also works on public WiFi with Wireguard**. It seems like cellular alone in iPad doesn't like tunnels or what ...

I tested this several times and from another place so I can be sure, iPad and iPhone can not somehow sneaky connect to my WiFi.

Can anyone explain to me this strange behaviour? Or better, did you find a way how to use just iPad cellular to make it work?

*One time I somehow managed to work but I can not remember what I did on iPad, something with iPad hotspot or data roaming or ...*

**Comment by stossy11** [comment]
As mentioned in the ReadMe JITStreamer only works over Wi-Fi (its an iOS Limitation.)

**Comment by jorycz** [comment]
Thanks. I was suspicious that Apple allows remote debugging only on WiFi.
