### ISSUE TITLE
Issue when running JITStreamer --pair

### ISSUE THREAD

**Issue by Malverde84** [stossy11/JITStreamer-2.0#23]
I'm on Windows and followed all of the instructions up to this point.

When I run JITStreamer --pair in an administrator Powershell, I get the following error:

(venv) PS C:\WINDOWS\system32\JITStreamer-2.0> JITStreamer --pair
Attempting to pair to a device! (Ctrl+C to stop)
[<PlistUsbmuxLockdownClient ID:****EDITED OUT**** VERSION:18.1 TYPE:iPhone17,1 PAIRED:True>]
Show Pairing file? [y/N]: y
Error opening directory: _path_normpath: path should be string, bytes or os.PathLike, not function

**Comment by stossy11** [comment]
dang it lmaooo

**Comment by stossy11** [comment]
ill fix it

**Comment by stossy11** [comment]
fixed
